#!/usr/bin/env python3
"""One-file stdio proxy that mirrors every tool from a remote MCP server."""

from __future__ import annotations

import os
import re
import sys
import tempfile
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from urllib.parse import urlsplit

from fastmcp import Client, FastMCP
from fastmcp.client.transports import StreamableHttpTransport
from fastmcp.server import create_proxy


def normalize_mcp_url(value: str, *, variable: str) -> str:
    """Accept a server root or exact MCP endpoint and return the endpoint URL."""
    normalized = value.strip().rstrip("/")
    parsed = urlsplit(normalized)
    if parsed.scheme not in {"http", "https"} or not parsed.netloc:
        raise ValueError(f"{variable} must be an absolute http:// or https:// URL")
    if parsed.username or parsed.password or parsed.query or parsed.fragment:
        raise ValueError(f"{variable} must not contain credentials, query, or fragment")
    path = parsed.path.rstrip("/")
    if path in {"", "/"}:
        return f"{normalized}/mcp"
    if not path.endswith("/mcp"):
        raise ValueError(f"{variable} must be a server root or end with /mcp")
    return normalized


@dataclass(frozen=True, slots=True)
class RemoteMcpConfig:
    """Connection settings for the shared remote MCP server."""

    url: str
    token: str = ""
    timeout_seconds: float = 120.0
    ca_file: str | None = None

    def __post_init__(self) -> None:
        if self.timeout_seconds <= 0:
            raise ValueError("CORPORATE_KB_MCP_TIMEOUT must be greater than zero")

    def client(self) -> Client[StreamableHttpTransport]:
        transport = StreamableHttpTransport(
            self.url,
            auth=self.token or None,
            verify=self.ca_file,
        )
        return Client(
            transport,
            name="corporate-kb-stdio-upstream",
            timeout=self.timeout_seconds,
        )


def _safe_path_component(value: str) -> str:
    normalized = re.sub(r"[^A-Za-z0-9._-]+", "-", value.strip()).strip(".-")
    if not normalized:
        raise ValueError("session_id and service_id must contain a safe path component")
    return normalized[:120]


def create_stdio_server(
    target: Any,
    *,
    upload_client_factory: Callable[[], Client[Any]] | None = None,
) -> FastMCP:
    """Mirror the complete upstream MCP surface through local stdio."""
    server = create_proxy(
        target,
        name="corporate-knowledge-stdio-proxy",
        instructions=(
            "This is a transparent proxy to the shared corporate knowledge MCP server. "
            "Tool names, schemas, annotations, and calls come from the upstream server."
        ),
        provider_error_strategy="raise",
    )
    if upload_client_factory is not None:

        @server.tool(
            name="kb_save_and_upload_ssot",
            description=(
                "Save SSOT Markdown generated by the local calling model under the user's "
                "temporary directory, then upload the same content to the remote SSOT session. "
                "Use finalize=false until the last service and finalize=true for the last one."
            ),
            annotations={
                "readOnlyHint": False,
                "destructiveHint": False,
                "idempotentHint": False,
                "openWorldHint": True,
            },
        )
        async def kb_save_and_upload_ssot(
            session_id: str,
            service_id: str,
            content: str,
            finalize: bool = True,
        ) -> dict[str, Any]:
            if len(content.strip()) < 100:
                raise ValueError("SSOT document must contain at least 100 characters")
            session_name = _safe_path_component(session_id)
            service_name = _safe_path_component(service_id)
            configured_root = os.environ.get("CORPORATE_KB_SSOT_TEMP_DIR", "").strip()
            temp_root = (
                Path(configured_root).expanduser()
                if configured_root
                else Path(tempfile.gettempdir()) / "corporate-kb-ssot"
            )
            destination = temp_root / session_name / f"{service_name}.md"
            destination.parent.mkdir(parents=True, exist_ok=True)
            temporary = destination.with_suffix(".md.tmp")
            temporary.write_text(content.strip() + "\n", encoding="utf-8")
            os.replace(temporary, destination)
            async with upload_client_factory() as upstream:
                uploaded = await upstream.call_tool(
                    "kb_generate_system_ssot",
                    {
                        "action": "submit",
                        "job_id": session_id,
                        "service_id": service_id,
                        "content": content,
                        "finalize": finalize,
                    },
                )
            if uploaded.is_error:
                raise RuntimeError(
                    f"SSOT was saved locally but remote upload failed: {uploaded.content}"
                )
            return {
                "status": "saved_and_uploaded",
                "local_path": str(destination.resolve()),
                "remote": uploaded.data,
            }

    return server


def config_from_environment() -> RemoteMcpConfig:
    """Load preferred MCP variables while preserving the old API variable names."""
    direct_url = os.environ.get("CORPORATE_KB_MCP_URL", "").strip()
    legacy_url = os.environ.get("CORPORATE_KB_API_URL", "").strip()
    raw_url = direct_url or legacy_url
    variable = "CORPORATE_KB_MCP_URL" if direct_url else "CORPORATE_KB_API_URL"
    if not raw_url:
        raise ValueError(
            "set CORPORATE_KB_MCP_URL to the shared server endpoint, for example "
            "http://10.20.30.40:8000/mcp"
        )
    token = os.environ.get("CORPORATE_KB_MCP_TOKEN")
    if token is None:
        token = os.environ.get("CORPORATE_KB_API_TOKEN", "")
    ca_file = os.environ.get("CORPORATE_KB_MCP_CA_FILE")
    if ca_file is None:
        ca_file = os.environ.get("CORPORATE_KB_API_CA_FILE") or None
    raw_timeout = os.environ.get("CORPORATE_KB_MCP_TIMEOUT")
    if raw_timeout is None:
        raw_timeout = os.environ.get("CORPORATE_KB_API_TIMEOUT", "120")
    try:
        timeout_seconds = float(raw_timeout)
    except ValueError:
        raise ValueError("CORPORATE_KB_MCP_TIMEOUT must be a number") from None
    return RemoteMcpConfig(
        url=normalize_mcp_url(raw_url, variable=variable),
        token=token,
        timeout_seconds=timeout_seconds,
        ca_file=ca_file,
    )


def main() -> None:
    """Start the local stdio endpoint; stdout stays reserved for MCP frames."""
    try:
        config = config_from_environment()
        server = create_stdio_server(
            config.client(),
            upload_client_factory=config.client,
        )
    except ValueError as exc:
        print(f"Configuration error: {exc}", file=sys.stderr)
        raise SystemExit(2) from exc

    try:
        server.run(transport="stdio", show_banner=False)
    except KeyboardInterrupt:
        return


if __name__ == "__main__":
    main()
